Repository s1mbi0se/alluxio, pull requests merged in 2020-07, with the labels that each got.

#10 fix: fix bug with duplicate members
  core/client/fs/src/main/java/alluxio/client/metrics/ClientMasterSync.java
Labels: bug

#11 docs: add comment documentation for methods used to mount an UFS path to an Alluxio path
  core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  core/client/fs/src/main/java/alluxio/client/file/FileSystemMasterClientPool.java
  core/common/src/main/java/alluxio/concurrent/CountingLatch.java
  core/common/src/main/java/alluxio/grpc/GrpcChannel.java
  core/common/src/main/java/alluxio/grpc/GrpcChannelBuilder.java
  core/common/src/main/java/alluxio/grpc/GrpcConnectionPool.java
  core/common/src/main/java/alluxio/security/authentication/AuthenticatedChannelClientDriver.java
  core/common/src/main/java/alluxio/security/authentication/plain/PlainSaslClientCallbackHandler.java
  core/common/src/main/java/alluxio/security/user/SimpleUserState.java
  core/common/src/main/java/alluxio/util/ConfigurationUtils.java
  core/common/src/main/java/alluxio/util/ThreadFactoryUtils.java
  core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
Labels: documentation, in progress

#13 fix: b2 pom parent version to 2.3.0
  underfs/b2/pom.xml
Labels: ready

#12 docs: add documentation for methods used to mount a UFS path to an Alluxio path
  core/client/fs/src/main/java/alluxio/client/file/ConfigHashSync.java
  core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java
  core/common/src/main/java/alluxio/AbstractClient.java
  core/common/src/main/java/alluxio/grpc/GrpcChannelBuilder.java
  core/common/src/main/java/alluxio/grpc/GrpcConnectionPool.java
  core/common/src/main/java/alluxio/metrics/MetricsSystem.java
  core/common/src/main/java/alluxio/retry/ExponentialTimeBoundedRetry.java
  core/common/src/main/java/alluxio/security/authentication/AuthType.java
  core/common/src/main/java/alluxio/security/authentication/plain/SaslClientHandlerPlain.java
  core/common/src/main/java/alluxio/util/ConfigurationUtils.java
  core/common/src/main/java/alluxio/util/SecurityUtils.java
  core/server/common/src/main/java/alluxio/master/MasterContext.java
  job/client/src/main/java/alluxio/worker/job/JobMasterClientContext.java
Labels: documentation, in progress

#14 Add documentation for methods used to mount a UFS path to an Alluxio path - part 5
  core/client/fs/src/main/java/alluxio/client/file/FileSystemMasterClient.java
  core/client/fs/src/main/java/alluxio/util/FileSystemOptions.java
  core/common/src/main/java/alluxio/AbstractClient.java
  core/common/src/main/java/alluxio/grpc/GrpcChannelKey.java
  core/common/src/main/java/alluxio/metrics/Metric.java
  core/common/src/main/java/alluxio/security/authentication/ChannelAuthenticator.java
  core/common/src/main/java/alluxio/security/user/BaseUserState.java
  core/common/src/main/java/alluxio/util/ConfigurationUtils.java
  core/common/src/main/java/alluxio/util/SecurityUtils.java
  core/common/src/main/java/alluxio/util/network/NettyUtils.java
  core/server/common/src/main/java/alluxio/master/transport/GrpcMessagingTransport.java
Labels: documentation, in progress

#15 docs: add documentation for methods used to mount an UFS path to an Alluxio path
  core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java
  core/common/src/main/java/alluxio/grpc/GrpcConnectionPool.java
  core/common/src/main/java/alluxio/grpc/GrpcUtils.java
  core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java
  core/common/src/main/java/alluxio/master/SingleMasterInquireClient.java
  core/common/src/main/java/alluxio/metrics/MetricsSystem.java
  core/common/src/main/java/alluxio/security/authentication/AuthenticatedChannelClientDriver.java
  core/common/src/main/java/alluxio/security/authentication/AuthenticatedChannelServerDriver.java
  core/common/src/main/java/alluxio/security/user/UserState.java
  core/common/src/main/java/alluxio/util/CommonUtils.java
  core/common/src/main/java/alluxio/util/network/NettyUtils.java
Labels: documentation, in progress

#16 docs: add documentation for methods used to mount an UFS path to an Alluxio path
  core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
  core/common/src/main/java/alluxio/AbstractClient.java
  core/common/src/main/java/alluxio/ClientContext.java
  core/common/src/main/java/alluxio/grpc/GrpcConnection.java
  core/common/src/main/java/alluxio/grpc/GrpcNetworkGroup.java
  core/common/src/main/java/alluxio/grpc/GrpcServerAddress.java
  core/common/src/main/java/alluxio/refresh/TimeoutRefresh.java
  core/common/src/main/java/alluxio/retry/CountingRetry.java
  core/common/src/main/java/alluxio/retry/ExponentialTimeBoundedRetry.java
  core/common/src/main/java/alluxio/retry/SleepingRetry.java
  core/common/src/main/java/alluxio/retry/TimeBoundedRetry.java
  core/common/src/main/java/alluxio/retry/TimeoutRetry.java
  core/common/src/main/java/alluxio/security/authentication/AbstractSaslClientHandler.java
  core/common/src/main/java/alluxio/security/authentication/ChannelAuthenticator.java
  core/common/src/main/java/alluxio/security/login/AlluxioLoginModule.java
  core/common/src/main/java/alluxio/security/login/LoginModuleConfigurationUtils.java
  core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java
  core/common/src/main/java/alluxio/util/FormatUtils.java
  shell/src/main/java/alluxio/cli/fs/command/MountCommand.java
  webui/npm-shrinkwrap.json
Labels: documentation, in progress

#17 docs: add documentation comments for methods used to mount a UFS path to an Alluxio path
  core/base/src/main/java/alluxio/AlluxioURI.java
  core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  core/common/src/main/java/alluxio/AbstractClient.java
  core/common/src/main/java/alluxio/grpc/GrpcChannelKey.java
  core/common/src/main/java/alluxio/grpc/GrpcConnectionPool.java
  core/common/src/main/java/alluxio/security/authentication/AuthenticationUserUtils.java
Labels: documentation, in progress

#18 docs: add documentation comments for methods used to mount an Under File Storage path to an Alluxio path
  core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
  core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  core/client/fs/src/main/java/alluxio/client/file/FileSystemMasterClientPool.java
  core/common/src/main/java/alluxio/AbstractClient.java
  core/common/src/main/java/alluxio/grpc/GrpcChannel.java
  core/common/src/main/java/alluxio/grpc/GrpcChannelBuilder.java
  core/common/src/main/java/alluxio/grpc/GrpcConnection.java
  core/common/src/main/java/alluxio/metrics/MetricsSystem.java
  core/common/src/main/java/alluxio/retry/CountingRetry.java
  core/common/src/main/java/alluxio/retry/SleepingRetry.java
  core/common/src/main/java/alluxio/retry/TimeBoundedRetry.java
  core/common/src/main/java/alluxio/retry/TimeoutRetry.java
  core/common/src/main/java/alluxio/security/authentication/AuthenticatedChannelClientDriver.java
  core/common/src/main/java/alluxio/security/user/UserState.java
  core/common/src/main/java/alluxio/util/network/NettyUtils.java
  core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
Labels: documentation, in progress

#19 docs: add documentation comments for methods used to mount a UFS path to an Alluxio path
  core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  core/client/fs/src/main/java/alluxio/client/file/FileSystemContextReinitializer.java
  core/common/src/main/java/alluxio/ClientContext.java
  core/common/src/main/java/alluxio/grpc/GrpcServerAddress.java
  core/common/src/main/java/alluxio/retry/ExponentialTimeBoundedRetry.java
  core/common/src/main/java/alluxio/security/login/AlluxioLoginModule.java
  core/common/src/main/java/alluxio/security/login/AppLoginModule.java
  core/common/src/main/java/alluxio/security/user/SimpleUserState.java
  core/common/src/main/java/alluxio/util/FormatUtils.java
  core/common/src/main/java/alluxio/util/network/NettyUtils.java
Labels: documentation, in progress

#20 docs: add documentation for methods used to mount a UFS path to an Alluxio path
  core/client/fs/src/main/java/alluxio/client/block/RetryHandlingBlockMasterClient.java
  core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java
  core/client/fs/src/main/java/alluxio/client/journal/RetryHandlingJournalMasterClient.java
  core/client/fs/src/main/java/alluxio/client/meta/RetryHandlingMetaMasterClient.java
  core/client/fs/src/main/java/alluxio/client/meta/RetryHandlingMetaMasterConfigClient.java
  core/client/fs/src/main/java/alluxio/client/metrics/RetryHandlingMetricsMasterClient.java
  core/common/src/main/java/alluxio/AbstractClient.java
  core/common/src/main/java/alluxio/grpc/GrpcChannelBuilder.java
  core/common/src/main/java/alluxio/grpc/GrpcConnectionPool.java
  core/common/src/main/java/alluxio/retry/RetryUtils.java
  core/common/src/main/java/alluxio/security/user/BaseUserState.java
  core/common/src/main/java/alluxio/util/ConfigurationUtils.java
  core/server/master/src/main/java/alluxio/master/meta/RetryHandlingMetaMasterMasterClient.java
  job/client/src/main/java/alluxio/client/job/RetryHandlingJobMasterClient.java
  job/server/src/main/java/alluxio/worker/job/RetryHandlingJobMasterClient.java
Labels: documentation, in progress

#22 docs: add doc comments for methods used to unmount an Alluxio path
  core/base/src/main/java/alluxio/AlluxioURI.java
  core/client/fs/src/main/java/alluxio/util/FileSystemOptions.java
  core/common/src/main/java/alluxio/AbstractClient.java
  core/common/src/main/java/alluxio/concurrent/CountingLatch.java
  core/common/src/main/java/alluxio/grpc/GrpcChannel.java
  core/common/src/main/java/alluxio/grpc/GrpcChannelBuilder.java
  core/common/src/main/java/alluxio/grpc/GrpcChannelKey.java
  core/common/src/main/java/alluxio/grpc/GrpcConnectionPool.java
  core/common/src/main/java/alluxio/master/MasterClientContext.java
  core/common/src/main/java/alluxio/metrics/MetricsSystem.java
  core/common/src/main/java/alluxio/retry/ExponentialTimeBoundedRetry.java
  core/common/src/main/java/alluxio/security/login/AppLoginModule.java
  core/common/src/main/java/alluxio/util/network/NettyUtils.java
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java
  shell/src/main/java/alluxio/cli/fs/FileSystemShellUtils.java
  shell/src/main/java/alluxio/cli/fs/command/UnmountCommand.java
Labels: documentation, in progress

#24 feat: fix documentation comments for methods used to mount a bucket in Alluxio
  core/base/src/main/java/alluxio/AlluxioURI.java
  core/client/fs/src/main/java/alluxio/client/block/RetryHandlingBlockMasterClient.java
  core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
  core/client/fs/src/main/java/alluxio/client/file/ConfigHashSync.java
  core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java
  core/client/fs/src/main/java/alluxio/client/journal/RetryHandlingJournalMasterClient.java
  core/client/fs/src/main/java/alluxio/client/meta/RetryHandlingMetaMasterClient.java
  core/client/fs/src/main/java/alluxio/client/meta/RetryHandlingMetaMasterConfigClient.java
  core/client/fs/src/main/java/alluxio/client/metrics/RetryHandlingMetricsMasterClient.java
  core/client/fs/src/main/java/alluxio/util/FileSystemOptions.java
  core/common/src/main/java/alluxio/AbstractClient.java
  core/common/src/main/java/alluxio/Client.java
  core/common/src/main/java/alluxio/concurrent/CountingLatch.java
  core/common/src/main/java/alluxio/grpc/GrpcChannelBuilder.java
  core/common/src/main/java/alluxio/grpc/GrpcChannelKey.java
  core/common/src/main/java/alluxio/grpc/GrpcConnectionPool.java
  core/common/src/main/java/alluxio/master/MasterClientContext.java
  core/common/src/main/java/alluxio/master/SingleMasterInquireClient.java
  core/common/src/main/java/alluxio/metrics/Metric.java
  core/common/src/main/java/alluxio/metrics/MetricsSystem.java
  core/common/src/main/java/alluxio/refresh/TimeoutRefresh.java
  core/common/src/main/java/alluxio/retry/CountingRetry.java
  core/common/src/main/java/alluxio/retry/ExponentialTimeBoundedRetry.java
  core/common/src/main/java/alluxio/retry/RetryUtils.java
  core/common/src/main/java/alluxio/retry/SleepingRetry.java
  core/common/src/main/java/alluxio/retry/TimeBoundedRetry.java
  core/common/src/main/java/alluxio/retry/TimeoutRetry.java
  core/common/src/main/java/alluxio/security/authentication/AuthenticatedChannelClientDriver.java
  core/common/src/main/java/alluxio/security/login/AlluxioLoginModule.java
  core/common/src/main/java/alluxio/security/login/AppLoginModule.java
  core/common/src/main/java/alluxio/security/user/BaseUserState.java
  core/common/src/main/java/alluxio/security/user/SimpleUserState.java
  core/common/src/main/java/alluxio/security/user/UserState.java
  core/common/src/main/java/alluxio/security/user/UserStateFactory.java
  core/common/src/main/java/alluxio/util/CommonUtils.java
  core/common/src/main/java/alluxio/util/ConfigurationUtils.java
  core/common/src/main/java/alluxio/util/SecurityUtils.java
  core/common/src/main/java/alluxio/util/network/NettyUtils.java
  core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java
  core/server/master/src/main/java/alluxio/master/meta/RetryHandlingMetaMasterMasterClient.java
  job/client/src/main/java/alluxio/client/job/RetryHandlingJobMasterClient.java
  job/server/src/main/java/alluxio/worker/job/RetryHandlingJobMasterClient.java
  shell/src/main/java/alluxio/cli/fs/FileSystemShellUtils.java
  shell/src/main/java/alluxio/cli/fs/command/MountCommand.java
  shell/src/main/java/alluxio/cli/fs/command/UnmountCommand.java
Labels: documentation, ready

#26 docs: add documentation comments for methods used to unmount a bucket
  core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
  core/common/src/main/java/alluxio/AbstractClient.java
  core/common/src/main/java/alluxio/ClientContext.java
  core/common/src/main/java/alluxio/grpc/GrpcChannelBuilder.java
  core/common/src/main/java/alluxio/grpc/GrpcChannelKey.java
  core/common/src/main/java/alluxio/grpc/GrpcConnectionKey.java
  core/common/src/main/java/alluxio/grpc/GrpcUtils.java
  core/common/src/main/java/alluxio/master/MasterClientContext.java
  core/common/src/main/java/alluxio/resource/DynamicResourcePool.java
  core/common/src/main/java/alluxio/security/user/BaseUserState.java
  core/common/src/main/java/alluxio/util/ConfigurationUtils.java
  shell/src/main/java/alluxio/cli/fs/command/AbstractFileSystemCommand.java
Labels: documentation, ready

#33 docs: add documentation for methods used to create a directory in Alluxio
  core/base/src/main/java/alluxio/collections/DirectedAcyclicGraphNode.java
  core/common/src/main/java/alluxio/util/CommonUtils.java
  core/server/master/src/main/java/alluxio/master/file/contexts/CreatePathContext.java
  core/server/master/src/main/java/alluxio/master/file/meta/InodeDirectoryView.java
  core/server/master/src/main/java/alluxio/master/file/meta/InodeLockList.java
  core/server/master/src/main/java/alluxio/master/file/meta/InodeTreePersistentState.java
  core/server/master/src/main/java/alluxio/master/file/meta/LockedInodePath.java
  core/server/master/src/main/java/alluxio/master/file/meta/MutableInode.java
Labels: documentation, ready

#34 docs: add documentation comments for methods used to create a directory in Alluxio
  core/common/src/main/java/alluxio/conf/AlluxioConfiguration.java
  core/common/src/main/java/alluxio/master/block/BlockId.java
  core/common/src/main/java/alluxio/retry/RetryPolicy.java
  core/common/src/main/java/alluxio/security/group/GroupMappingService.java
  core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
  core/server/master/src/main/java/alluxio/master/file/DefaultPermissionChecker.java
  core/server/master/src/main/java/alluxio/master/file/RpcContext.java
  core/server/master/src/main/java/alluxio/master/file/contexts/CreatePathContext.java
  core/server/master/src/main/java/alluxio/master/file/meta/InodeDirectoryIdGenerator.java
  core/server/master/src/main/java/alluxio/master/file/meta/InodeTreePersistentState.java
  core/server/master/src/main/java/alluxio/master/file/meta/LockedInodePath.java
  core/server/master/src/main/java/alluxio/master/file/meta/MutableInode.java
  core/server/master/src/main/java/alluxio/master/file/meta/MutableInodeDirectory.java
  core/server/master/src/main/java/alluxio/master/metastore/InodeStore.java
  core/server/master/src/main/java/alluxio/master/metastore/heap/HeapInodeStore.java
  integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseOptions.java
Labels: documentation, ready

#36 Implement fine-grained logging for 5 Alluxio scopes + 10 file system commands
  logging/pom.xml
  logging/src/main/java/alluxio/logging/base/FlowLoggingAspect.java
  logging/src/main/java/alluxio/logging/scope/ScopeJobMasterFlowLoggingAspect.java
  logging/src/main/java/alluxio/logging/scope/ScopeJobWorkerFlowLoggingAspect.java
  logging/src/main/java/alluxio/logging/scope/ScopeMasterFlowLoggingAspect.java
  logging/src/main/java/alluxio/logging/scope/ScopeProxyFlowLoggingAspect.java
  logging/src/main/java/alluxio/logging/scope/ScopeWorkerFlowLoggingAspect.java
  logging/src/main/java/alluxio/logging/scope/base/ScopeFlowLoggingAspect.java
  logging/src/main/java/alluxio/logging/shell/FsChgrpFlowLoggingAspect.java
  logging/src/main/java/alluxio/logging/shell/FsChmodFlowLoggingAspect.java
  logging/src/main/java/alluxio/logging/shell/FsChownFlowLoggingAspect.java
  logging/src/main/java/alluxio/logging/shell/FsFreeFlowLoggingAspect.java
  logging/src/main/java/alluxio/logging/shell/FsLoadFlowLoggingAspect.java
  logging/src/main/java/alluxio/logging/shell/FsLsFlowLoggingAspect.java
  logging/src/main/java/alluxio/logging/shell/FsMkdirFlowLoggingAspect.java
  logging/src/main/java/alluxio/logging/shell/FsMountFlowLoggingAspect.java
  logging/src/main/java/alluxio/logging/shell/FsMvFlowLoggingAspect.java
  logging/src/main/java/alluxio/logging/shell/FsPersistFlowLoggingAspect.java
  logging/src/main/java/alluxio/logging/shell/FsRmFlowLoggingAspect.java
  logging/src/main/java/alluxio/logging/shell/FsUnmountFlowLoggingAspect.java
  logging/src/main/java/alluxio/logging/shell/base/FsFlowLoggingAspect.java
  pom.xml
Labels: feature, ready

#38 Add documentation comments for methods used to run 'fs ls' in Alluxio
  core/base/src/main/java/alluxio/security/authorization/AccessControlList.java
  core/common/src/main/java/alluxio/wire/Configuration.java
  core/common/src/main/java/alluxio/wire/FileInfo.java
Labels: changes requested, documentation, ready

#39 Add documentation comments for methods used to run 'fs ls' in Alluxio
  core/base/src/main/java/alluxio/security/authorization/AccessControlList.java
  core/base/src/main/java/alluxio/security/authorization/DefaultAccessControlList.java
  core/base/src/main/java/alluxio/util/StreamUtils.java
  core/common/src/main/java/alluxio/grpc/GrpcUtils.java
  core/common/src/main/java/alluxio/wire/FileInfo.java
Labels: documentation, ready

#40 Add last documentation comments for methods used to run 'fs ls ...' in Alluxio
  core/base/src/main/java/alluxio/security/authorization/DefaultAccessControlList.java
  core/client/fs/src/main/java/alluxio/client/file/FileSystemMasterClient.java
  core/client/fs/src/main/java/alluxio/util/FileSystemOptions.java
  core/common/src/main/java/alluxio/wire/FileInfo.java
  shell/src/main/java/alluxio/cli/fs/command/LsCommand.java
Labels: documentation, ready

#41 Add all documentation comments for methods used to run 'fs mv' in Alluxio
  core/base/src/main/java/alluxio/util/OSUtils.java
Labels: documentation, ready

#42 Improve AspectJ logging, removing unused advices
  logging/src/main/java/alluxio/logging/shell/FsMkdirFlowLoggingAspect.java
  logging/src/main/java/alluxio/logging/shell/FsMountFlowLoggingAspect.java
  logging/src/main/java/alluxio/logging/shell/FsUnmountFlowLoggingAspect.java
Labels: documentation, ready

#43 Add documentation comments for methods used to run 'fs load' - 1/2
  core/client/fs/src/main/java/alluxio/util/FileSystemOptions.java
  core/common/src/main/java/alluxio/grpc/GrpcConnectionPool.java
  core/common/src/main/java/alluxio/resource/DynamicResourcePool.java
  core/common/src/main/java/alluxio/retry/RetryUtils.java
  core/common/src/main/java/alluxio/wire/FileBlockInfo.java
Labels: documentation, ready
